#!/usr/bin/python3
def calc_factorise(number):
    div = 2
    while (number % div != 0):
        div += 1
    return (number // div)


if __name__ == '__main__':
    from sys import argv

    if len(argv) != 2:
        exit(1)
    with open(argv[1], "r") as file:
        for line in file:
            number = int(line[:-1])
            result = calc_factorise(number)
            print(f"{number}={result}*{number // result}")
